apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: slack-connector
  labels:
    strimzi.io/cluster: camel
spec:
  class: org.apache.camel.kafkaconnector.slack.CamelSlackSourceConnector
  tasksMax: 1
  config:
    topics: slack.general
    value.converter: io.apicurio.registry.utils.converter.ExtJsonConverter
    value.converter.schemas.enable: 'false'
    value.converter.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.AutoRegisterIdStrategy
    value.converter.apicurio.registry.url: 'http://registry-service-qknsz:8080/api'
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.utils.serde.JsonSchemaKafkaSerializer
    value.converter.apicurio.registry.converter.deserializer: io.apicurio.registry.utils.serde.JsonSchemaKafkaDeserializer
    camel.source.endpoint.maxResults: 1
    camel.source.path.channel: general
    camel.source.endpoint.token: xoxb-1086662136182-1078705155239-264xnfcdnlSlNIec1yFSv1W3